name: DevSecOps Security Pipeline

on: [push]

jobs:
    security-scans:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                fetch-depth: 0


            - name: Scan for Secrets
              uses: gitleaks/gitleaks-action@v2
              env:
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

            - name: Install dependencies
              run: npm install

            - name: Sync open source Scan
              uses: snyk/actions/node@master
              env:
                SNYK_TOKEN: ${{ ee4ee18e-bacf-4045-8129-8768aa7b516e }}
              with:
                command: test

            - name: Synk code scan
              uses: snyk/actions/node@master
              env:
                SNYK_TOKEN: ${{ ee4ee18e-bacf-4045-8129-8768aa7b516e}}
              with:
                command: code test